import { Container, Title } from "@mantine/core";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <Container>
          <Title>Welcome to Goober</Title>
          <Link href="/request-ride">Request a Ride</Link>
          <br />
          <Link href="/cancel-ride">Cancel a Ride</Link>
          <br />
          <Link href="/view-rides">View Your Rides</Link>
          <br />
          <Link href="/driver-dashboard">Driver Dashboard</Link>
        </Container>
      </main>
    </>
  );
}
