import { ReactNode } from "react";
import Head from "next/head";

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Goober - Your Ride Awaits</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main
        className="flex min-h-screen flex-col items-center justify-center bg-cover bg-center"
        style={{ backgroundImage: "url('/background.jpg')" }}
      >
        {children}
      </main>
    </>
  );
};

export default Layout;
